name: alfred_cli
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0
  analyzer: ^1.7.1
  source_gen: ^1.0.2
  args: ^2.1.1
  ansicolor: ^2.0.1
  recase: ^4.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
